paperless:
  config:
    PAPERLESS_TASK_WORKERS: "1"
  secrets:
    PAPERLESS_SECRET_KEY: "superlongtestingkeyforcideployment,butwhatalongtestingkeyihopethisbuilddoespass"
    PAPERLESS_ADMIN_PASSWORD: "strongadminpasswordthatisstrongerthantherock"

persistence:
  data:
    size: 1Gi
  media:
    size: 1Gi
  export:
    size: 1Gi
  consume:
    size: 1Gi

cnpg:
  storage:
    size: 1Gi
