apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-config
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless
data:
  {{- range $key, $val := .Values.paperless.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
