{{- if not .Values.paperless.existingSecret }}
{{- include "paperless-ngx.validate" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.secretName" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless
type: Opaque
stringData:
  {{- range $key, $val := .Values.paperless.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
