{{- if not .Values.paperless.existingSecret }}
{{- include "paperless-ngx.validate" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.secretName" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: {{ .Values.paperless.secrets.PAPERLESS_SECRET_KEY | quote }}
  PAPERLESS_ADMIN_USER: {{ .Values.paperless.secrets.PAPERLESS_ADMIN_USER | quote }}
  PAPERLESS_ADMIN_PASSWORD: {{ .Values.paperless.secrets.PAPERLESS_ADMIN_PASSWORD | quote }}
  PAPERLESS_ADMIN_MAIL: {{ .Values.paperless.secrets.PAPERLESS_ADMIN_MAIL | quote }}
{{- end }}
