{{- if and .Values.redis.enabled .Values.redis.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-redis
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: paperless
      ports:
        - protocol: TCP
          port: redis
{{- end }}
